### ISSUE TITLE
[BUG] mac无法安装服务模式

### ISSUE THREAD

**Issue by wuqi-y** [clash-verge-rev/clash-verge-rev#1974]
### 问题描述 / Describe the bug

直接点击安装服务模式失败
<img width="800" alt="image" src="https://github.com/user-attachments/assets/10395057-2155-417c-b67b-57a34ff0ce90">
failed to install service with error: Password:thread 'main' panicked at src/install.rs:28:60: Unable to copy service file: Os { code: 20, kind: NotADirectory, message: "Not a directory" } note: run with RUST_BACKTRACE=1 environment variable to display a backtrace bash: line 1: 3193 Done echo "abc2002522" 3194 Abort trap: 6 | sudo -S /Applications/Clash\ Verge.app/Contents/Resources/resources/install-service 

### 软件版本 / Verge Version

v1.7.7

### 复现步骤 / To Reproduce

直接点击安装服务模式失败
<img width="800" alt="image" src="https://github.com/user-attachments/assets/10395057-2155-417c-b67b-57a34ff0ce90">

### 操作系统 / OS

Windows

### 操作系统版本 / OS Version

macos 14.6.1 (23G93)

### 日志 / Log

2024-11-01 21:54:58 ERROR - failed to install service with error: Password:thread 'main' panicked at src/install.rs:28:60:
Unable to copy service file: Os { code: 20, kind: NotADirectory, message: "Not a directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
bash: line 1: 22735 Done                    echo "abc2002522"
     22736 Abort trap: 6           | sudo -S /Applications/Clash\ Verge.app/Contents/Resources/resources/install-service

2024-11-01 21:54:58 ERROR - failed to connect to the Clash Verge Service
2024-11-01 21:54:59 INFO - [mihomo]: time="2024-11-01T21:54:59.564878+08:00" level=info msg="[TCP] 127.0.0.1:50547(Google Chrome Helper) --> mtalk.google.com:5228 match DomainKeyword(google) using 谷歌服务[日本JP-T]"

2024-11-01 21:54:59 INFO - [mihomo]: time="2024-11-01T21:54:59.704173+08:00" level=info msg="[TCP] 127.0.0.1:50553(com.apple.Safari.SafeBrowsing.Service) --> safebrowsing.googleapis.com:443 match DomainKeyword(google) using 谷歌服务[日本JP-T]"

2024-11-01 21:54:59 INFO - [mihomo]: time="2024-11-01T21:54:59.977288+08:00" level=info msg="[TCP] 127.0.0.1:50555(Google Chrome Helper) --> mtalk.google.com:5228 match DomainKeyword(google) using 谷歌服务[日本JP-T]"

2024-11-01 21:55:00 INFO - [mihomo]: time="2024-11-01T21:55:00.115746+08:00" level=info msg="[TCP] 127.0.0.1:50557(com.apple.Safari.SafeBrowsing.Service) --> safebrowsing.googleapis.com:443 match DomainKeyword(google) using 谷歌服务[日本JP-T]"

2024-11-01 21:55:00 INFO - [mihomo]: time="2024-11-01T21:55:00.735823+08:00" level=info msg="[TCP] 127.0.0.1:50563(com.apple.Safari.SafeBrowsing.Service) --> safebrowsing.googleapis.com:443 match DomainKeyword(google) using 谷歌服务[日本JP-T]"

2024-11-01 21:55:00 ERROR - failed to connect to the Clash Verge Service

**Comment by Tychristine** [comment]
不再接受1.x版本的反馈

**Comment by wonfen** [comment]
请下载安装2.0版
