### ISSUE TITLE
[BUG] Ubuntu22.04 自启动无响应 / tty模式启动主线程panic

### ISSUE THREAD

**Issue by leauny** [clash-verge-rev/clash-verge-rev#321]
### Describe the bug

开启自启动后开机没有任何反应。将log level改为trace后只有一行输出。自行在gnome终端启动后又是正常的。

```
2024-01-29 09:25:18 DEBUG [clash_verge::utils::init] - try to delete log files, day: 30
```

而切换为tty模式启动时，主线程会panic，不清楚是否是这个原因导致的自启失败。

报错如下：

```rust
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.3/src/lib.rs:2021:55:
called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: Display parsing error"
stack backtrace:
   0:     0x5593a16a1f8f - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5593a16a1f8f - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5593a16a1f8f - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5593a16a1f8f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5593a14f9b90 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x5593a14f9b90 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x5593a166cb1e - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x5593a16a382e - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5593a16a382e - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5593a16a3135 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x5593a16a405b - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x5593a16a405b - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x5593a16a3b9c - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x5593a16a3af6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5593a16a3ae1 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x5593a1340f04 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x5593a1341472 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:     0x5593a13a9159 - tauri_runtime_wry::Wry<T>::init::h4e13ebf5f1f67f40
  18:     0x5593a13f2bfa - tauri::app::Builder<R>::build::hc8f7cabbc75f9f0a
  19:     0x5593a14b01ff - clash_verge::main::hc1374afca6e8b16e
  20:     0x5593a13ba541 - std::sys_common::backtrace::__rust_begin_short_backtrace::h92eca59f8d21e1fc
  21:     0x5593a13bcfd9 - std::rt::lang_start::hf5c223f1d56c162c
  22:     0x7fd97a229d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  23:     0x7fd97a229e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  24:     0x5593a1360eea - _start
  25:                0x0 - <unknown>
```

### To Reproduce

进入tty模式（如，`Ctrl+Alt+F3`），执行clash-verge即可

### Platform

Linux

### System Version

Linux lenovo 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Software Version

1.4.10

### Log

```
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.3/src/lib.rs:2021:55:
called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: Display parsing error"
stack backtrace:
   0:     0x5593a16a1f8f - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5593a16a1f8f - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5593a16a1f8f - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5593a16a1f8f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5593a14f9b90 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x5593a14f9b90 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x5593a166cb1e - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x5593a16a382e - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5593a16a382e - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5593a16a3135 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x5593a16a405b - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x5593a16a405b - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x5593a16a3b9c - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x5593a16a3af6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5593a16a3ae1 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x5593a1340f04 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x5593a1341472 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:     0x5593a13a9159 - tauri_runtime_wry::Wry<T>::init::h4e13ebf5f1f67f40
  18:     0x5593a13f2bfa - tauri::app::Builder<R>::build::hc8f7cabbc75f9f0a
  19:     0x5593a14b01ff - clash_verge::main::hc1374afca6e8b16e
  20:     0x5593a13ba541 - std::sys_common::backtrace::__rust_begin_short_backtrace::h92eca59f8d21e1fc
  21:     0x5593a13bcfd9 - std::rt::lang_start::hf5c223f1d56c162c
  22:     0x7fd97a229d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  23:     0x7fd97a229e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  24:     0x5593a1360eea - _start
  25:                0x0 - <unknown>
```

**Comment by GitatHub** [comment]
Update and reboot, then try AppImage, instead of RPM installing the app.
In my Ubuntu 22.04 LTS, it runs but with very high CPU usage when GUI is shown.

**Comment by LongTaiJun** [comment]
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/12383024/d9c90d56-e2fc-43a8-968b-c3302980b93e)
`# journalctl |grep clash
Feb 04 09:43:59 etix dbus-daemon[1174]: [session uid=1000 pid=1174] Activating service name='org.gnome.Nautilus' requested by ':1.202' (uid=1000 pid=36172 comm="gio open /home/tyson/.local/share/io.github.clash-" label="unconfined")
Feb 04 09:45:08 etix systemd[1118]: app-gnome-clash\x2dverge-4848.scope: Consumed 1d 1h 28min 26.259s CPU time.
Feb 04 09:46:55 etix clash-verge.desktop[1692]: thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.3/src/lib.rs:2021:55:
Feb 04 09:46:55 etix clash-verge.desktop[1692]: called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: X11 server connection timed out because it was unreachable"
Feb 04 09:46:55 etix clash-verge.desktop[1692]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Feb 04 09:46:56 etix update-notifier-crash[2389]: clash-verge
`
I also encountered the same problem.
