### ISSUE TITLE
[BUG] 似乎在x86版本中, 无法启用TUN模式

### ISSUE THREAD

**Issue by blufish1234** [clash-verge-rev/clash-verge-rev#351]
### Describe the bug

如题, 在使用x86版本时无法启动TUN模式, 报错内容如下: 
![image](https://github.com/clash-verge-rev/clash-verge-rev/assets/97332474/8c38f14c-ea68-4aab-91d8-13e07bff056c)

### To Reproduce

1. 安装并启动Clash Verge x86 版本
2. 启用TUN模式
3. 出现错误

### Platform

Windows

### System Version

Window 10 专业版 22H2 19045.3930

### Software Version

1.5.0

### Log

2024-02-06 15:55:46 INFO - [clash]: time="2024-02-06T15:55:46.9809706+08:00" level=info msg="Start initial configuration in progress"

2024-02-06 15:55:46 INFO - [clash]: time="2024-02-06T15:55:46.9989576+08:00" level=info msg="Geodata Loader mode: memconservative"

2024-02-06 15:55:46 INFO - [clash]: time="2024-02-06T15:55:46.9989576+08:00" level=info msg="Geosite Matcher implementation: succinct"

2024-02-06 15:55:47 INFO - [clash]: time="2024-02-06T15:55:47.0176071+08:00" level=info msg="Initial configuration complete, total time: 18ms"

2024-02-06 15:55:47 INFO - [clash]: time="2024-02-06T15:55:47.0176264+08:00" level=info msg="Sniffer is closed"

2024-02-06 15:55:47 INFO - [clash]: time="2024-02-06T15:55:47.0186742+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9097"

2024-02-06 15:55:47 INFO - [clash]: time="2024-02-06T15:55:47.0186742+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:22337"

2024-02-06 15:55:47 INFO - [clash]: time="2024-02-06T15:55:47.0192374+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:22336"

2024-02-06 15:55:47 INFO - [clash]: time="2024-02-06T15:55:47.0192374+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:22335"

2024-02-06 15:55:47 INFO - [clash]: time="2024-02-06T15:55:47.0211743+08:00" level=info msg="Start initial Compatible provider default"

2024-02-06 15:55:49 INFO - [clash]: time="2024-02-06T15:55:49.4169027+08:00" level=info msg="HTTP proxy listening at: [::]:22337"

2024-02-06 15:55:49 INFO - [clash]: time="2024-02-06T15:55:49.418014+08:00" level=info msg="SOCKS proxy listening at: [::]:22336"

2024-02-06 15:55:49 INFO - [clash]: time="2024-02-06T15:55:49.418014+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:22335"

2024-02-06 15:56:08 INFO - [clash]: time="2024-02-06T15:56:08.4127886+08:00" level=info msg="Start initial configuration in progress"

2024-02-06 15:56:08 INFO - [clash]: time="2024-02-06T15:56:08.4133231+08:00" level=info msg="Geodata Loader mode: memconservative"

2024-02-06 15:56:08 INFO - [clash]: time="2024-02-06T15:56:08.4133231+08:00" level=info msg="Geosite Matcher implementation: succinct"

2024-02-06 15:56:08 INFO - [clash]: time="2024-02-06T15:56:08.4275309+08:00" level=info msg="Initial configuration complete, total time: 13ms"

2024-02-06 15:56:08 INFO - [clash]: time="2024-02-06T15:56:08.4275309+08:00" level=info msg="Sniffer is closed"

2024-02-06 15:56:08 INFO - [clash]: time="2024-02-06T15:56:08.4424432+08:00" level=warning msg="[TUN] default interface changed by monitor,  => 乙太網路"

2024-02-06 15:56:09 INFO - [clash]: time="2024-02-06T15:56:09.0843318+08:00" level=info msg="[TUN] Tun adapter listening at: Meta([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: true, ip stack: gVisor"

2024-02-06 15:56:09 ERROR - [clash]: panic: unaligned 64-bit atomic operation

2024-02-06 15:56:09 ERROR - [clash]: 

2024-02-06 15:56:09 ERROR - [clash]: goroutine 161 [running]:

2024-02-06 15:56:09 ERROR - [clash]: runtime/internal/atomic.panicUnaligned()

2024-02-06 15:56:09 ERROR - [clash]: 	runtime/internal/atomic/unaligned.go:8 +0x2b

2024-02-06 15:56:09 ERROR - [clash]: runtime/internal/atomic.Load64(0xb92f2d4)

2024-02-06 15:56:09 ERROR - [clash]: 	runtime/internal/atomic/atomic_386.s:225 +0x10

2024-02-06 15:56:09 ERROR - [clash]: github.com/metacubex/sing-tun.(*NativeTun).ReadFunc(0xb92f200, 0xbae1f88)

2024-02-06 15:56:09 ERROR - [clash]: 	github.com/metacubex/sing-tun@v0.2.1-0.20240130042529-1f983547e9d4/tun_windows.go:377 +0xe7

2024-02-06 15:56:09 ERROR - [clash]: github.com/metacubex/sing-tun.(*WintunEndpoint).dispatchLoop(0xb8a4c90)

2024-02-06 15:56:09 ERROR - [clash]: 	github.com/metacubex/sing-tun@v0.2.1-0.20240130042529-1f983547e9d4/tun_windows_gvisor.go:55 +0x79

2024-02-06 15:56:09 ERROR - [clash]: created by github.com/metacubex/sing-tun.(*WintunEndpoint).Attach in goroutine 125

2024-02-06 15:56:09 ERROR - [clash]: 	github.com/metacubex/sing-tun@v0.2.1-0.20240130042529-1f983547e9d4/tun_windows_gvisor.go:48 +0xcc

2024-02-06 15:56:09 INFO - error sending request for url (http://127.0.0.1:9097/configs): connection error: 遠端主機已強制關閉一個現存的連線。 (os error 10054)
2024-02-06 15:56:09 INFO - clash core terminated
2024-02-06 15:56:11 INFO - error sending request for url (http://127.0.0.1:9097/configs): error trying to connect: tcp connect error: 無法連線，因為目標電腦拒絕連線。 (os error 10061)
2024-02-06 15:56:13 INFO - error sending request for url (http://127.0.0.1:9097/configs): error trying to connect: tcp connect error: 無法連線，因為目標電腦

**Comment by blufish1234** [comment]
我已经测试过 x64(32位)版本可以正常开启TUN模式

**Comment by liu1435533520** [comment]
我的也报错：

2024-02-06 17:03:11 ERROR - failed to connect to the Clash Verge Service
2024-02-06 17:03:21 INFO - clash core terminated
2024-02-06 17:03:23 INFO - error sending request for url (http://127.0.0.1:9098/configs): connection error: 远程主机强迫关闭了一个现有的连接。 (os error 10054)
2024-02-06 17:03:25 INFO - error sending request for url (http://127.0.0.1:9098/configs): error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)
2024-02-06 17:03:28 INFO - recover clash core
2024-02-06 17:03:28 INFO - error sending request for url (http://127.0.0.1:9098/configs): error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)
2024-02-06 17:03:30 INFO - error sending request for url (http://127.0.0.1:9098/configs): error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)
2024-02-06 17:03:32 ERROR - error sending request for url (http://127.0.0.1:9098/configs): error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)

**Comment by Jerry0527** [comment]
一样的问题，1.4.10 x64 可以正常使用 tun 模式

**Comment by henry99a** [comment]
我省1.5。0后也是这样报错


02-07 23:39:22WARNING
[TUN] default interface changed by monitor, => 以太网 4
02-07 23:39:38WARNING
Start Tun interface timeout: Cannot create a file when that file already exists. [retrying 1/3]
02-07 23:39:38INFO
[TUN] Tun adapter listening at: Meta([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: true, ip stack: gVisor

**Comment by cangming99** [comment]
1.5.0以后我也遇到了同样的问题，我一直用的懒人配置，对于配置可以说是完全不懂了，但还是试图提供一些线索。
```yaml
tun:
  enable: true
  stack: gVisor
  ```
  stack使用mixed和system时我都遇到了这个问题，改为gVisor就没遇到了，目前能用，回退旧版本可以使用mixed。

**Comment by Jerry0527** [comment]
@cangming99 @blufish1234 最新的1.5.1 已经修好这个问题了，卸载重装后， tun 模式正常，

感谢开发者，新年快乐

**Comment by cangming99** [comment]
> @cangming99 @blufish1234 最新的1.5.1 已经修好这个问题了，卸载重装后， tun 模式正常，
> 
> 感谢开发者，新年快乐

坏了只有我更新后还存在问题吗，先用gVisor凑合一下，要不就只能用系统代理了

**Comment by MystiPanda** [comment]
> 我装的x64版本，x86版本没测试

那你在这里回复什么呢？我已经看到你回复了好几个issue了，你确定人家遇到的问题跟你一样吗你就回复？就这个issue来说，标题写的清清楚楚x86，你装的又不是x86你在这回复个什么劲？

**Comment by Jerry0527** [comment]
行的，我都去删掉，8了个8

**Comment by wonfen** [comment]
内核报错了，请到meta那边反馈： https://github.com/MetaCubeX/mihomo/issues
```
2024-02-06 15:56:09 INFO - [clash]: time="2024-02-06T15:56:09.0843318+08:00" level=info msg="[TUN] Tun adapter listening at: Meta([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: true, ip stack: gVisor"

2024-02-06 15:56:09 ERROR - [clash]: panic: unaligned 64-bit atomic operation

2024-02-06 15:56:09 ERROR - [clash]:

2024-02-06 15:56:09 ERROR - [clash]: goroutine 161 [running]:

2024-02-06 15:56:09 ERROR - [clash]: runtime/internal/atomic.panicUnaligned()

2024-02-06 15:56:09 ERROR - [clash]: runtime/internal/atomic/unaligned.go:8 +0x2b

2024-02-06 15:56:09 ERROR - [clash]: runtime/internal/atomic.Load64(0xb92f2d4)

2024-02-06 15:56:09 ERROR - [clash]: runtime/internal/atomic/atomic_386.s:225 +0x10

2024-02-06 15:56:09 ERROR - [clash]: github.com/metacubex/sing-tun.(*NativeTun).ReadFunc(0xb92f200, 0xbae1f88)

2024-02-06 15:56:09 ERROR - [clash]: github.com/metacubex/sing-tun@v0.2.1-0.20240130042529-1f983547e9d4/tun_windows.go:377 +0xe7

2024-02-06 15:56:09 ERROR - [clash]: github.com/metacubex/sing-tun.(*WintunEndpoint).dispatchLoop(0xb8a4c90)

2024-02-06 15:56:09 ERROR - [clash]: github.com/metacubex/sing-tun@v0.2.1-0.20240130042529-1f983547e9d4/tun_windows_gvisor.go:55 +0x79

2024-02-06 15:56:09 ERROR - [clash]: created by github.com/metacubex/sing-tun.(*WintunEndpoint).Attach in goroutine 125

2024-02-06 15:56:09 ERROR - [clash]: github.com/metacubex/sing-tun@v0.2.1-0.20240130042529-1f983547e9d4/tun_windows_gvisor.go:48 +0xcc

```

**Comment by wonfen** [comment]
无进一步反馈，关闭。
